class L10N:
    LANGS = {
        "en": "🇬🇧 English",
        "bn": "🇧🇩 বাংলা",
        "hi": "🇮🇳 हिन्दी",
        "ru": "🇷🇺 Русский",
        "ar": "🇸🇦 العربية",
        "es": "🇪🇸 Español",
        "de": "🇩🇪 Deutsch",
        "fr": "🇫🇷 Français",
        "pt": "🇧🇷 Português",
        "id": "🇮🇩 Bahasa",
        "tr": "🇹🇷 Türkçe",
        "fa": "🇮🇷 فارسی",
        "uz": "🇺🇿 O'zbekcha",
        "kk": "🇰🇿 Қазақша",
        "uk": "🇺🇦 Українська",
        "zh": "🇨🇳 中文",
        "vi": "🇻🇳 Tiếng Việt",
        "th": "🇹🇭 ไทย",
        "ja": "🇯🇵 日本語",
        "ko": "🇰🇷 한국어",
        "my": "🇲🇲 မြန်မာ",
    }

    T = {
        "en": {
            "menu_earnings": "💰 Earnings",
            "menu_promote": "📢 Promote",
            "menu_checks": "📋 Checks",
            "menu_cabinet": "👤 My Cabinet",
            "menu_sub_check": "🛡 Subscription Check",
            "menu_stats": "📊 Our Bots & Stats",
            "menu_links": "🔗 Useful Links",
            "menu_instruction": "ℹ️ Instruction",
            "menu_withdraw": "💸 Withdraw",
            "welcome": "👋 Welcome to <b>{bot_name}</b>, {first_name}!\n\n🚀 Complete tasks, earn GRAM coins, and promote your channels instantly!",
            "lang_changed": "✅ Language changed successfully!",
            "not_started": "⚠️ Please tap /start first.",
            "text_only": "⚠️ Please send this as a text message.",
            "cabinet": "👤 <b>Your Cabinet:</b>\n\n🆔 My ID: <code>{user_id}</code>\n🏅 Level: {level_emoji} {level}\n💰 Balance: <code>{balance:,.0f}</code> GRAM\n⚡ XP: {xp}/{next_xp}\n🎯 Tasks Done: {tasks}",
            "btn_replenish": "🪙 Replenish Balance",
            "btn_referral": "👥 Referral System",
            "btn_level": "📊 Level System",
            "btn_tasks": "📋 My Tasks",
            "btn_lang": "🌐 Change Language",
            "btn_notif_on": "🔕 Disable Notifications",
            "btn_notif_off": "🔔 Enable Notifications",
            "btn_back": "◀️ Back",
            "tasks_title": "🎯 <b>Available Tasks</b>\n\nComplete any task below to earn GRAM:",
            "no_tasks": "🎯 No active tasks right now. Check back soon!",
            "task_verified": "🎉 <b>Task Verified!</b>\n\n💰 +<code>{reward:,.0f}</code> GRAM\n⚡ +{xp} XP",
            "task_failed": "❌ Verification failed! Please join first and try again.",
            "task_already": "❌ You already completed this task!",
            "task_limit": "❌ Task limit reached.",
            "task_premium_only": "⭐ This task is for Telegram Premium users only.",
            "task_open": "🚀 Open Link",
            "task_verify": "✅ Verify",
            "task_back": "◀️ Back to List",
            "promote_title": "📢 <b>Create Promotion Campaign</b>\n\nSelect the task type:",
            "promote_name": "📝 Send the campaign title:",
            "promote_target": "🔗 Send the channel/group username (e.g. <code>@mychannel</code>) or link:",
            "promote_link": "🔗 Send the link users should open:",
            "promote_bot_token": "🤖 Send your bot token for verification:",
            "promote_premium": "⭐ <b>Premium Targeting</b>\n\nTarget only Telegram Premium users? Rewards will be 2x.",
            "promote_premium_yes": "⭐ Premium Only (2x)",
            "promote_premium_no": "👥 All Users",
            "promote_reward": "💰 Send reward per user (GRAM coins):\n\n💡 Suggested: <code>{suggested:,}</code>\n📊 Range: <code>{min:,}</code> – <code>{max:,}</code>",
            "promote_slots": "👥 Send total number of users (slots):",
            "promote_created": "✅ <b>Campaign Created!</b>\n\n📢 {title}\n💰 Reward: <code>{reward:,.0f}</code> GRAM\n👥 Slots: {slots}\n💳 Cost: <code>{cost:,.0f}</code> GRAM",
            "promote_insufficient": "❌ Insufficient balance!\n\nRequired: <code>{required:,.0f}</code> GRAM\nYour balance: <code>{balance:,.0f}</code> GRAM",
            "promote_duplicate": "⚠️ You already have an active campaign for this target!",
            "add_slots_btn": "➕ Add Slots to Existing",
            "new_campaign_btn": "🆕 Create New Campaign",
            "cancel_btn": "❌ Cancel",
            "cancelled": "❌ Cancelled.",
            "wd_locked": "🔒 <b>Withdrawal Locked</b>\n\nReach Level {required} to unlock withdrawals.\nYour current level: {current}",
            "wd_prompt": "💸 <b>Withdrawal</b>\n\nMin: <code>{min:,.0f}</code> GRAM\nMax: <code>{max:,.0f}</code> GRAM\nYour balance: <code>{balance:,.0f}</code> GRAM\n\nSend the amount:",
            "wd_invalid": "❌ Amount must be between <code>{min:,.0f}</code> and <code>{max:,.0f}</code> GRAM.",
            "wd_insufficient": "❌ Insufficient balance.",
            "wd_method": "💳 Choose your payment method:",
            "wd_details": "📝 Send your payment details (wallet/account):",
            "wd_submitted": "✅ Withdrawal request submitted!\n\nAmount: <code>{amount:,.0f}</code> GRAM\nStatus: Pending admin approval",
            "checks_menu": "📋 <b>Checks System</b>\n\nCreate shareable GRAM vouchers or redeem existing ones.",
            "check_create_btn": "🎫 Create a Check",
            "check_activate_btn": "💳 Activate a Check",
            "check_amount": "💰 Send GRAM amount per activation:",
            "check_activations": "👥 Send number of activations:",
            "check_password": "🔐 Set a password (or type <code>skip</code>):",
            "check_created": "✅ <b>Check Created!</b>\n\n🎫 Code: <code>{code}</code>\n💰 Amount: <code>{amount:,.0f}</code> GRAM\n👥 Activations: {activations}\n🔗 Link:\n<code>{link}</code>",
            "check_redeem_prompt": "🎫 Send the check code:",
            "check_password_prompt": "🔐 This check requires a password. Send it:",
            "check_invalid": "❌ Invalid or expired code.",
            "check_wrong_pw": "❌ Wrong password.",
            "check_redeemed": "✅ Check redeemed! +<code>{amount:,.0f}</code> GRAM",
            "ref_title": "👥 <b>Referral System</b>\n\nEarn <code>{base:,.0f}</code> GRAM per direct referral!\n\n📊 <b>Tier Bonuses:</b>\n• Tier 1 (Direct): 8%\n• Tier 2: 5%\n• Tier 3: 2%\n\n📈 Direct referrals: <code>{direct}</code>\n💰 Total earned: <code>{earned:,.0f}</code> GRAM\n\n🔗 Your link:\n<code>{link}</code>",
            "level_title": "📊 <b>Level System</b>\n\n🏅 Level: {emoji} <code>{level}</code>\n⚡ Total XP: <code>{xp:,}</code>\n📈 Progress: {progress}\n\n💡 Withdraw unlocks at Level {min_level}.",
            "stats": "📊 <b>Boost Gram Statistics</b>\n\n👥 Users: <code>{users:,}</code>\n📢 Active campaigns: <code>{active:,}</code>\n✅ Tasks completed: <code>{completed:,}</code>\n💎 Total paid: <code>{paid:,.0f}</code> GRAM",
            "rules_title": "⚠️ <b>Earning Rules</b>",
            "rules_forbidden": "🚫 <b>Forbidden:</b>\n• Unsubscribing within 7 days\n• Removing reactions\n• Multiple accounts\n• Fake traffic / bots\n• Automation tools",
            "rules_penalty": "⚡ <b>Penalties:</b>\n• Task ban: 7 days\n• Repeat ban: 7 more days\n• Full revocation of task reward",
            "instruction": "ℹ️ <b>How to use Boost Gram</b>\n\n1️⃣ Complete tasks under 💰 Earnings\n2️⃣ Promote your channel under 📢 Promote\n3️⃣ Gift/redeem under 📋 Checks\n4️⃣ Manage in 👤 My Cabinet\n5️⃣ Invite friends for 5,000 GRAM + tier bonuses",
            "links": "🔗 <b>Useful Links</b>\n\n• Bot: @{bot}\n• Support: Contact admin",
            "sub_check": "🛡 <b>Subscription Verification</b>\n\nAll subscriptions verified live via Telegram Bot API.\n\n📌 Channel/Group owner must add @{bot} as <b>Administrator</b>.",
            "retention_warning": "⚠️ <b>Retention Warning!</b>\n\nYou left <b>{target}</b> before 7 days.\nRejoin now to avoid penalty:\n{link}",
            "retention_penalty": "🚫 <b>Penalty Applied!</b>\n\nYou left {target}. Reward of <code>{reward:,.0f}</code> GRAM has been revoked.",
            "error_generic": "❌ Something went wrong. Try again.",
        },
        "bn": {
            "menu_earnings": "💰 আয়",
            "menu_promote": "📢 প্রচার করুন",
            "menu_checks": "📋 চেক",
            "menu_cabinet": "👤 আমার কেবিনেট",
            "menu_sub_check": "🛡 সাবস্ক্রিপশন চেক",
            "menu_stats": "📊 আমাদের বট ও পরিসংখ্যান",
            "menu_links": "🔗 দরকারী লিংক",
            "menu_instruction": "ℹ️ নির্দেশিকা",
            "menu_withdraw": "💸 উইথড্র",
            "welcome": "👋 <b>{bot_name}</b>-এ আপনাকে স্বাগতম, {first_name}!\n\n🚀 টাস্ক সম্পন্ন করুন, GRAM কয়েন আয় করুন এবং আপনার চ্যানেল প্রমোট করুন!",
            "lang_changed": "✅ ভাষা সফলভাবে পরিবর্তন হয়েছে!",
            "not_started": "⚠️ প্রথমে /start চাপুন।",
            "text_only": "⚠️ টেক্সট মেসেজ পাঠান।",
            "cabinet": "👤 <b>আপনার কেবিনেট:</b>\n\n🆔 আমার আইডি: <code>{user_id}</code>\n🏅 লেভেল: {level_emoji} {level}\n💰 ব্যালেন্স: <code>{balance:,.0f}</code> GRAM\n⚡ XP: {xp}/{next_xp}\n🎯 সম্পন্ন টাস্ক: {tasks}",
            "btn_replenish": "🪙 ব্যালেন্স রিচার্জ",
            "btn_referral": "👥 রেফারেল সিস্টেম",
            "btn_level": "📊 লেভেল সিস্টেম",
            "btn_tasks": "📋 আমার টাস্কসমূহ",
            "btn_lang": "🌐 ভাষা পরিবর্তন",
            "btn_notif_on": "🔕 নোটিফিকেশন বন্ধ করুন",
            "btn_notif_off": "🔔 নোটিফিকেশন চালু করুন",
            "btn_back": "◀️ ফিরে যান",
            "tasks_title": "🎯 <b>উপলব্ধ টাস্কসমূহ</b>\n\nনিচের যেকোনো টাস্ক সম্পন্ন করে GRAM আয় করুন:",
            "no_tasks": "🎯 এখন কোনো টাস্ক নেই। শীঘ্রই আবার চেক করুন!",
            "task_verified": "🎉 <b>টাস্ক ভেরিফাইড!</b>\n\n💰 +<code>{reward:,.0f}</code> GRAM\n⚡ +{xp} XP",
            "task_failed": "❌ যাচাই ব্যর্থ! প্রথমে জয়েন করুন তারপর চেষ্টা করুন।",
            "task_already": "❌ আপনি ইতিমধ্যে এই টাস্ক সম্পন্ন করেছেন!",
            "task_limit": "❌ টাস্ক লিমিট পূর্ণ হয়েছে।",
            "task_premium_only": "⭐ এই টাস্ক শুধুমাত্র Telegram Premium ইউজারদের জন্য।",
            "task_open": "🚀 লিংক খুলুন",
            "task_verify": "✅ যাচাই করুন",
            "task_back": "◀️ ফিরে যান",
            "promote_title": "📢 <b>প্রচার ক্যাম্পেইন তৈরি</b>\n\nটাস্ক টাইপ নির্বাচন করুন:",
            "promote_name": "📝 ক্যাম্পেইন টাইটেল পাঠান:",
            "promote_target": "🔗 চ্যানেল/গ্রুপ ইউজারনেম পাঠান (যেমন <code>@mychannel</code>) বা লিংক:",
            "promote_link": "🔗 ইউজাররা যে লিংকে যাবে সেটি পাঠান:",
            "promote_bot_token": "🤖 ভেরিফিকেশনের জন্য আপনার বট টোকেন পাঠান:",
            "promote_premium": "⭐ <b>প্রিমিয়াম টার্গেটিং</b>\n\nশুধু Telegram Premium ইউজার টার্গেট করবেন? রিওয়ার্ড ২x হবে।",
            "promote_premium_yes": "⭐ শুধু প্রিমিয়াম (২x)",
            "promote_premium_no": "👥 সব ইউজার",
            "promote_reward": "💰 প্রতি ইউজার রিওয়ার্ড পাঠান (GRAM কয়েন):\n\n💡 প্রস্তাবিত: <code>{suggested:,}</code>\n📊 রেঞ্জ: <code>{min:,}</code> – <code>{max:,}</code>",
            "promote_slots": "👥 মোট ইউজার সংখ্যা (স্লট) পাঠান:",
            "promote_created": "✅ <b>ক্যাম্পেইন তৈরি হয়েছে!</b>\n\n📢 {title}\n💰 রিওয়ার্ড: <code>{reward:,.0f}</code> GRAM\n👥 স্লট: {slots}\n💳 খরচ: <code>{cost:,.0f}</code> GRAM",
            "promote_insufficient": "❌ অপর্যাপ্ত ব্যালেন্স!\n\nপ্রয়োজন: <code>{required:,.0f}</code> GRAM\nআপনার: <code>{balance:,.0f}</code> GRAM",
            "promote_duplicate": "⚠️ এই টার্গেটের জন্য ইতিমধ্যে একটি সক্রিয় ক্যাম্পেইন আছে!",
            "add_slots_btn": "➕ বিদ্যমান ক্যাম্পেইনে স্লট যোগ",
            "new_campaign_btn": "🆕 নতুন ক্যাম্পেইন",
            "cancel_btn": "❌ বাতিল",
            "cancelled": "❌ বাতিল হয়েছে।",
            "wd_locked": "🔒 <b>উইথড্র লকড</b>\n\nলেভেল {required} এ পৌঁছান।\nআপনার লেভেল: {current}",
            "wd_prompt": "💸 <b>উইথড্র</b>\n\nসর্বনিম্ন: <code>{min:,.0f}</code> GRAM\nসর্বোচ্চ: <code>{max:,.0f}</code> GRAM\nআপনার ব্যালেন্স: <code>{balance:,.0f}</code> GRAM\n\nপরিমাণ পাঠান:",
            "wd_invalid": "❌ পরিমাণ <code>{min:,.0f}</code> থেকে <code>{max:,.0f}</code> GRAM এর মধ্যে হতে হবে।",
            "wd_insufficient": "❌ অপর্যাপ্ত ব্যালেন্স।",
            "wd_method": "💳 পেমেন্ট মেথড নির্বাচন করুন:",
            "wd_details": "📝 আপনার পেমেন্ট ডিটেইলস পাঠান (ওয়ালেট/অ্যাকাউন্ট):",
            "wd_submitted": "✅ উইথড্র রিকোয়েস্ট জমা হয়েছে!\n\nপরিমাণ: <code>{amount:,.0f}</code> GRAM\nস্ট্যাটাস: অ্যাডমিন অনুমোদনের অপেক্ষায়",
            "checks_menu": "📋 <b>চেক সিস্টেম</b>\n\nশেয়ারযোগ্য GRAM ভাউচার তৈরি করুন বা রিডিম করুন।",
            "check_create_btn": "🎫 চেক তৈরি করুন",
            "check_activate_btn": "💳 চেক অ্যাক্টিভেট করুন",
            "check_amount": "💰 প্রতি অ্যাক্টিভেশনে GRAM পরিমাণ পাঠান:",
            "check_activations": "👥 কতবার অ্যাক্টিভেট করা যাবে:",
            "check_password": "🔐 পাসওয়ার্ড সেট করুন (বা <code>skip</code> টাইপ করুন):",
            "check_created": "✅ <b>চেক তৈরি হয়েছে!</b>\n\n🎫 কোড: <code>{code}</code>\n💰 পরিমাণ: <code>{amount:,.0f}</code> GRAM\n👥 অ্যাক্টিভেশন: {activations}\n🔗 লিংক:\n<code>{link}</code>",
            "check_redeem_prompt": "🎫 চেক কোড পাঠান:",
            "check_password_prompt": "🔐 এই চেকের জন্য পাসওয়ার্ড প্রয়োজন। পাঠান:",
            "check_invalid": "❌ অকার্যকর বা মেয়াদোত্তীর্ণ কোড।",
            "check_wrong_pw": "❌ ভুল পাসওয়ার্ড।",
            "check_redeemed": "✅ চেক রিডিম হয়েছে! +<code>{amount:,.0f}</code> GRAM",
            "ref_title": "👥 <b>রেফারেল সিস্টেম</b>\n\nপ্রতি সরাসরি রেফারেলে <code>{base:,.0f}</code> GRAM!\n\n📊 <b>টিয়ার বোনাস:</b>\n• টিয়ার ১ (সরাসরি): ৮%\n• টিয়ার ২: ৫%\n• টিয়ার ৩: ২%\n\n📈 সরাসরি রেফারেল: <code>{direct}</code>\n💰 মোট আয়: <code>{earned:,.0f}</code> GRAM\n\n🔗 আপনার লিংক:\n<code>{link}</code>",
            "level_title": "📊 <b>লেভেল সিস্টেম</b>\n\n🏅 লেভেল: {emoji} <code>{level}</code>\n⚡ মোট XP: <code>{xp:,}</code>\n📈 অগ্রগতি: {progress}\n\n💡 লেভেল {min_level} এ উইথড্র আনলক হবে।",
            "stats": "📊 <b>Boost Gram পরিসংখ্যান</b>\n\n👥 ইউজার: <code>{users:,}</code>\n📢 সক্রিয় ক্যাম্পেইন: <code>{active:,}</code>\n✅ সম্পন্ন টাস্ক: <code>{completed:,}</code>\n💎 মোট পরিশোধ: <code>{paid:,.0f}</code> GRAM",
            "rules_title": "⚠️ <b>আয়ের নিয়মাবলী</b>",
            "rules_forbidden": "🚫 <b>নিষিদ্ধ:</b>\n• ৭ দিনের আগে আনসাবস্ক্রাইব\n• দেওয়া রিঅ্যাকশন তুলে নেওয়া\n• একাধিক অ্যাকাউন্ট\n• ভুয়া ট্রাফিক / বট\n• অটোমেশন টুল",
            "rules_penalty": "⚡ <b>লঙ্ঘনের পরিণতি:</b>\n• টাস্ক বান: ৭ দিন\n• পুনরায় বান: আরো ৭ দিন\n• সম্পূর্ণ রিওয়ার্ড বাতিল",
            "instruction": "ℹ️ <b>Boost Gram ব্যবহারের নির্দেশিকা</b>\n\n১️⃣ 💰 আয় থেকে টাস্ক সম্পন্ন করুন\n২️⃣ 📢 প্রচার করুন থেকে চ্যানেল প্রমোট করুন\n৩️⃣ 📋 চেক থেকে গিফট/রিডিম করুন\n৪️⃣ 👤 আমার কেবিনেট থেকে ম্যানেজ করুন\n৫️⃣ বন্ধু ইনভাইট করে ৫,০০০ GRAM + টিয়ার বোনাস পান",
            "links": "🔗 <b>দরকারী লিংক</b>\n\n• বট: @{bot}\n• সাপোর্ট: অ্যাডমিনের সাথে যোগাযোগ করুন",
            "sub_check": "🛡 <b>সাবস্ক্রিপশন ভেরিফিকেশন</b>\n\nসব সাবস্ক্রিপশন লাইভ Telegram Bot API দিয়ে যাচাই হয়।\n\n📌 চ্যানেল/গ্রুপ মালিককে @{bot} কে <b>অ্যাডমিন</b> বানাতে হবে।",
            "retention_warning": "⚠️ <b>রিটেনশন সতর্কতা!</b>\n\nআপনি ৭ দিনের আগে <b>{target}</b> ছেড়েছেন।\nপেনাল্টি এড়াতে এখনই rejoin করুন:\n{link}",
            "retention_penalty": "🚫 <b>পেনাল্টি প্রয়োগ!</b>\n\nআপনি {target} ছেড়েছেন। <code>{reward:,.0f}</code> GRAM বাতিল হয়েছে।",
            "error_generic": "❌ কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
        },
    }

    for _code in LANGS:
        if _code not in T:
            T[_code] = {}

    @classmethod
    def get(cls, lang: str, key: str, **kw) -> str:
        text = (
            cls.T.get(lang, {}).get(key)
            or cls.T["en"].get(key)
            or f"[{key}]"
        )
        try:
            return text.format(**kw)
        except (KeyError, IndexError):
            return text


def t(lang: str, key: str, **kw) -> str:
    return L10N.get(lang, key, **kw)
